name: Build Nix Flake

on:
  push:
    branches: [ main ]
    paths:
      - 'flake.nix'
      - 'flake.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'flake.nix'
      - 'flake.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build development shell
        run: |
          nix build .#devShells.x86_64-linux.default --dry-run
          echo "✅ Development shell can be built"

      - name: Build profile-cpp app
        run: |
          nix build .#apps.x86_64-linux.profile-cpp --dry-run
          echo "✅ Profile-cpp app can be built"

      - name: Check if flake is valid
        run: |
          nix flake check
          echo "✅ Flake check passed"

      - name: Build Docker image with Nix flake
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: cpp-nix-dev:latest
          file: Dockerfile

      - name: Verify Docker image
        run: |
          docker run --rm cpp-nix-dev:latest nix --version
          echo "✅ Docker image contains Nix"
          docker run --rm cpp-nix-dev:latest bash -c "grep 'experimental-features' /etc/nix/nix.conf"
          echo "✅ Docker image has flakes enabled" 